### PR TITLE
Updated documentation

### PR DESCRIPTION
**Pull request by rickecon**
This PR updates the documentation for OG-USA.

### CODE REVIEW

**Comment by jdebacker** [comment]
@rickecon Thanks for this.  Are you ok with having the doc here rather than a link pointing towards your OGUSAdoc repo?

**Comment by rickecon** [comment]
@jdebacker . Yes. We have to have the PDF of the documentation here because the `OGUSAdoc` repo with all the images and LaTeX source is a private repository. We can't link to it.

**Comment by rickecon** [comment]
Oh, and I also noticed that this commit has some changes I made to the `.gitignore` to ignore Dask files and the big `micro_data_` files.

**Comment by jdebacker** [comment]
@rickecon got it. thanks.

**Pull request merged**
